apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus
  namespace: monitor-app
  labels:
    app: prometheus
spec:
  storageClassName: '{{var.storage.class.fast}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
