apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prometheus
  namespace: monitor-app
  labels:
    app: prometheus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: {{var.ingress.class.private}}
  tls:
    - hosts:
        - prometheus.{{var.global.private.host}}
      secretName: {{var.global.private.tls-name}}
  rules:
    - host: prometheus.{{var.global.private.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-prometheus
                port:
                  name: prometheus
