apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-data
  namespace: core-middle
  labels:
    type: postgres
spec:
  storageClassName: cluster-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
