apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-data
  namespace: core-middle
  labels:
    app: postgres
spec:
  storageClassName: '{{var.storage.class.security}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
