apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-ganesha-local
  labels:
    app: nfs-ganesha
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2000Gi
  local:
    # 指定挂载的目录
    path: /share
    # 配置节点亲和性
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - '{{var.nfs.local-path.node-name}}' # 指定部署在 {{var.nfs.local-path.node-name}} 节点上，可根据实际需求更改
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-nfs-ganesha-local
  volumeMode: Filesystem
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nfs-ganesha-local
  labels:
    app: nfs-ganesha
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-ganesha-local
  namespace: nfs-ganesha
  labels:
    app: nfs-ganesha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
  storageClassName: sc-nfs-ganesha-local
  volumeMode: Filesystem
  volumeName: pv-nfs-ganesha-local
