apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: rook-nfs
  namespace: rook-nfs
  labels:
    app: rook-nfs
spec:
  replicas: 1
  exports:
    - name: local-share
      server:
        accessMode: ReadWrite
        squash: none
      persistentVolumeClaim:
        claimName: pvc-rook-nfs-local
  annotations:
    rook: nfs
