apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-mariadb
  namespace: core-middle
  labels:
    app: mariadb
spec:
  serviceName: mariadb-server
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.8
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mariadb-root
                  key: password
            - name: MARIADB_ROOT_HOST
              value: "%"
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - |
                  mysqladmin -uroot -p$MARIADB_ROOT_PASSWORD ping &> /dev/null
            initialDelaySeconds: 20
            periodSeconds: 2
            timeoutSeconds: 5
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: pvc-mariadb-data
