apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-elastic-data
  namespace: core-middle
  labels:
    app: elastic
spec:
  storageClassName: '{{var.storage.class.default}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
