apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-elastic
  namespace: core-middle
  labels:
    app: elastic
spec:
  serviceName: svc-elastic
  selector:
    matchLabels:
      app: elastic
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
          ports:
            - containerPort: 9200
              name: api
            - containerPort: 9300
              name: cluster-port
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: conf-elastic
                  key: jvm.ops
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-elastic
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-elastic
                  key: password
            - name: 'xpack.security.enabled'
              valueFrom:
                configMapKeyRef:
                  name: conf-elastic
                  key: 'xpack.security.enabled'

      volumes:
        - name: elastic-data
          persistentVolumeClaim:
            claimName: pvc-elastic-data
