pages:
  image:
    name: d7z-team/asciidoc-static-pages:v2
  script:
    - git checkout -b pages
    - pages --output public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
