pages:
  image:
    name: ghcr.io/d7z-team/asciidoc-static-pages:v2
  before_script:
    - "curl $CUSTOM_CONFIG_PATH -o value-custom.properties 1>/dev/null 2>&1 ||:"
  script:
    - git checkout -b pages
    - pages --output public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
