pages:
  info:
    title: "All In Kubernetes"
    home: 'https://github.com/d7z-project/all-in-kubernetes'
  location:
    menu: '/MENU.adoc'
    main: '/README.adoc'
    icon: '/logo.svg'
    output: '/build'
  conf: # 功能配置
    source_url: 'https://github.com/d7z-project/all-in-kubernetes/tree/{{file.commit.id}}/'
    attr_ext: # 变量注入的文件后缀
      - adoc
      - sh
      - txt
      - yaml
      - yml
      - ldif
  attr_files:
    - value.properties
    - value-custom.properties
    - version.properties
