apiVersion: v1
kind: Secret
metadata:
  name: secret-gitlab-ci-token
  namespace: gitlab-ci
  labels:
    app: gitlab-ci
stringData:
  # 请填写 Gitlab CI 的 Token
  GITLAB_CI_TOKEN: '{{var.gitlab.ci.token}}' # <1>
