apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab-ci-runner
  namespace: dev-ops
  labels:
    app: gitlab-ci
spec:
  selector:
    matchLabels:
     app: gitlab-ci
  updateStrategy:
    type: RollingUpdate
  replicas: 2
  serviceName: gitlab-ci-runner
  template:
    metadata:
      labels:
        app: gitlab-ci
    spec:
      volumes:
        - name: gitlab-ci-runner-scripts
          projected:
            sources:
              - configMap:
                  name: conf-gitlab-ci-scripts
                  items:
                    - key: run.sh
                      path: run.sh
                      mode: 0755
                    - key: default.toml
                      path: default.toml
                      mode: 0755
        - name: gitlab-ci-runner-certs
          projected:
            sources:
              - secret:
                  name: '{{var.global.public.tls-name}}'
                  items:
                    - key: 'tls.crt'
                      path: 'tls.crt'
                      mode: 0777
      serviceAccountName: gitlab-ci
      containers:
        - image: 'registry.gitlab.com/gitlab-org/gitlab-runner:alpine-v15.5.0'
          name: gitlab-ci-runner
          command:
            - /scripts/run.sh
          envFrom:
            - configMapRef:
                name: conf-gitlab-ci
            - secretRef:
                name: secret-gitlab-ci-token
          ports:
            - containerPort: 9100
              name: http-metrics
              protocol: TCP
          volumeMounts:
            - name: gitlab-ci-runner-scripts
              mountPath: "/scripts"
              readOnly: true
            - name: gitlab-ci-runner-certs
              mountPath: "/certs"
              readOnly: true
      restartPolicy: Always
