apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitlab-data
  namespace: core-app
  labels:
    type: gitlab
spec:
  storageClassName: cluster-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitlab-redis
  namespace: core-app
  labels:
    type: gitlab
spec:
  storageClassName: cluster-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
