apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab-server
  namespace: core-app
  labels:
    app: gitlab-server
    type: gitlab
spec:
  serviceName: gitlab-server
  selector:
    matchLabels:
      app: gitlab-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab-server
        type: gitlab
    spec:
      containers:
        - name: gitlab-redis
          image: redis:6.2
          volumeMounts:
            - name: gitlab-redis
              mountPath: /data
        - name: gitlab-server
          image: sameersbn/gitlab:15.1.2
          volumeMounts:
            - name: gitlab-data
              mountPath: /home/git/data
          env:
            - name: GITLAB_SSH_PORT
              value: "22"
            - name: GITLAB_PORT
              value: "443"
            - name: GITLAB_HTTPS
              value: "true"
            - name: SSL_SELF_SIGNED
              value: "true"
            - name: GITLAB_HOST
              valueFrom:
                configMapKeyRef:
                  name: conf-gitlab
                  key: gitlab-host
            - name: GITLAB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-gitlab
                  key: root-password
            - name: GITLAB_SECRETS_DB_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secret-gitlab
                  key: db-key-secrets
            - name: GITLAB_SECRETS_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secret-gitlab
                  key: session-key-secrets
            - name: GITLAB_SECRETS_OTP_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secret-gitlab
                  key: otp-key-secrets
            - name: GITLAB_TIMEZONE
              value: Beijing
            - name: GITLAB_PACKAGES_ENABLED
              value: 'false'
            - name: GITLAB_REGISTRY_ENABLED
              value: 'false'
            - name: GITLAB_PAGES_ENABLED
              value: 'false'
            - name: DB_HOST
              value: "postgres.core-middle.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: conf-gitlab
                  key: db-name
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: conf-gitlab
                  key: db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-gitlab
                  key: db-password
            - name: REDIS_HOST
              value: "127.0.0.1"
            - name: REDIS_PORT
              value: "6379"
            - name: LDAP_ENABLED
              value: "true"
            - name: LDAP_LABEL
              value: "LDAP"
            - name: "LDAP_HOST"
              valueFrom:
                configMapKeyRef:
                  key: ldap_host
                  name: ldap-global-conf
            - name: LDAP_PORT
              value: "389"
            - name: LDAP_UID
              value: "uid"
            - name: LDAP_BLOCK_AUTO_CREATED_USERS
              value: "true"
            - name: LDAP_ACTIVE_DIRECTORY
              value: "false"
            - name: LDAP_METHOD
              value: "plain"
            - name: LDAP_BIND_DN
              valueFrom:
                secretKeyRef:
                  name: ldap-secret-service
                  key: user-dn
            - name: LDAP_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ldap-secret-service
            - name: LDAP_BASE
              valueFrom:
                configMapKeyRef:
                  key: ldap_user_dn
                  name: ldap-global-conf
            - name: LDAP_USER_FILTER
              valueFrom:
                configMapKeyRef:
                  key: ldap-user-filter
                  name: conf-gitlab
      volumes:
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: pvc-gitlab-data
        - name: gitlab-redis
          persistentVolumeClaim:
            claimName: pvc-gitlab-redis
