apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-lam
  namespace: core-system
  labels:
    app: lam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lam
  template:
    metadata:
      labels:
        app: lam
    spec:
      containers:
        - name: lam
          image: docker.io/ldapaccountmanager/lam:8.1
          ports:
            - containerPort: 80
          env:
            - name: LAM_SKIP_PRCONFIGURE
              value: "true"
            - name: LDAP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: conf-ldap
                  key: LDAP_DOMAIN
            - name: LDAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: conf-ldap
                  key: LDAP_URL
            - name: LDAP_BASE_DN
              valueFrom:
                configMapKeyRef:
                  name: conf-ldap
                  key: LDAP_BASE_DN
            - name: LDAP_USERS_DN
              valueFrom:
                configMapKeyRef:
                  name: conf-ldap
                  key: LDAP_USERS_DN
            - name: LDAP_GROUPS_DN
              valueFrom:
                configMapKeyRef:
                  name: conf-ldap
                  key: LDAP_GROUPS_DN
            - name: LAM_LANG
              value: zh_CN
            - name: LAM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-ldap-admin
                  key: LDAP_ADMIN_PASSWORD
