apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lam
  namespace: core-system
  labels:
    app: lam
  annotations:
    # 重写路径
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{var.ingress.class.private}}
  tls:
    - hosts:
        - ldap.{{var.global.private.host}} # <1>
      secretName: {{var.global.private.tls-name}}  # <2>
  rules:
    - host: ldap.{{var.global.private.host}}  # <3>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-lam  # <4>
                port:
                  name: web
