apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lam
  namespace: core-system
  labels:
    app: lam
  annotations:
    # 重写路径
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - lam.{{deploy-host-}} # <1>
      secretName: tls-{{deploy-host-name}}  # <2>
  rules:
    - host: lam.{{deploy-host-}}  # <3>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-lam  # <4>
                port:
                  name: web
