apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lam
  namespace: core-system
  labels:
    app: lam
  annotations:
    # 重写路径
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-private
  tls:
    - hosts:
        - ldap.internal.d7z.net # <1>
      secretName: tls-pri-d7z  # <2>
  rules:
    - host: ldap.internal.d7z.net  # <3>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-lam  # <4>
                port:
                  name: web
