apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-gitlab
  namespace: core-app
  labels:
    app: gitlab
data:
  db-name: 'gitlabhq_production' # <1>
  db-user: 'gitlab'  # <2>
  gitlab-host: gitlab.{{var.global.pub-host}} # <3>
  gitlab-pages-host: pages.{{var.global.pub-host}} # <3>
  ldap-user-filter: '(|(memberOf=cn=admin,ou=groups,dc=cluster,dc=local)(memberOf=cn=gitlab,ou=groups,dc=cluster,dc=local))' # <4>
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-gitlab
  namespace: core-app
  labels:
    app: gitlab
stringData:
  db-password: 'password'# <5>
  root-password: '{{var.gitlab.root.password}}' # <6>
  db-key-secrets: '{{var.gitlab.db-secrets}}'  # <7>
  session-key-secrets: '{{var.gitlab.session-secrets}}'  # <7>
  otp-key-secrets: '{{var.gitlab.otp-secrets}}' # <7>
  pages-key-secrets: '{{var.gitlab.pages-secrets}}' # <7>
