apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-gitlab
  namespace: core-app
  labels:
    app: gitlab
data:
  db-name: 'gitlabhq_production' # <1>
  db-user: 'gitlab'  # <2>
  gitlab-host: gitlab.d7z.net # <3>
  gitlab-pages-host: pages.d7z.net # <3>
  ldap-user-filter: '(|(memberOf=cn=admin,ou=groups,dc=cluster,dc=local)(memberOf=cn=gitlab,ou=groups,dc=cluster,dc=local))' # <4>
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-gitlab
  namespace: core-app
  labels:
    app: gitlab
stringData:
  db-password: 'password'# <5>
  root-password: 'gitlab-root-password' # <6>
  db-key-secrets: 'long-and-random-alpha-numeric-string'  # <7>
  session-key-secrets: 'long-and-random-alpha-numeric-string'  # <7>
  otp-key-secrets: 'long-and-random-alpha-numeric-string' # <7>
  pages-key-secrets: 'long-and-random-alpha-numeric-string' # <7>
