apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-gitlab
  namespace: core-app
  labels:
    app: gitlab
data:
  DB_NAME: 'gitlabhq_production' # <1>
  DB_USER: 'gitlab'  # <2>
  HOST: gitlab.d7z.net # <3>
  PAGES_HOST: pages.d7z.net # <3>
  LDAP_USERS_FILTER: '(|(memberOf=cn=admin,ou=groups,dc=cluster,dc=local)(memberOf=cn=develop,ou=groups,dc=cluster,dc=local))' # <4>
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-gitlab
  namespace: core-app
  labels:
    app: gitlab
stringData:
  DB_PASS: 'password'# <5>
  ADMIN_PASS: 'gitlab-root-password' # <6>
  DB_KEY_SECRETS: 'long-and-random-alpha-numeric-string'  # <7>
  SESSION_KEY_SECRETS: 'long-and-random-alpha-numeric-string'  # <7>
  OTP_KEY_SECRETS: 'long-and-random-alpha-numeric-string' # <7>
  PAGES_KEY_SECRETS: 'long-and-random-alpha-numeric-string' # <7>
