apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitlab-data
  namespace: core-app
  labels:
    app: gitlab
spec:
  storageClassName: '{{var.storage.class.security}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitlab-redis
  namespace: core-app
  labels:
    app: gitlab
spec:
  storageClassName: '{{var.storage.class.security}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
