apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gitlab
  namespace: core-app
  labels:
    app: gitlab
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - gitlab.{{var.deploy.host}}
      secretName: tls-{{var.deploy.host.name}}
  rules:
    - host: gitlab.{{var.deploy.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-gitlab
                port:
                  name: gitlab-web
