apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-reflector
  namespace: test
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default"
data:
  test: 'ok'
