apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-ldap
  namespace: core-system
  labels:
    type: ldap
  annotations: # <1>
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kube-system,default,core-system,core-middleware,core-app,share-app,monitor-app"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kube-system,default,core-system,core-middleware,core-app,share-app,monitor-app"
data:
  ldap-name: "Kubernetes Cluster LDAP Server"
  ldap-domain: 'cluster.local'
  ldap-host: 'service-ldap.core-system.svc.cluster.local'
  ldap-url: 'ldap://svc-ldap.core-system.svc.cluster.local:389'
  ldap-base-dn: 'dc=cluster,dc=local'
  ldap-user-ou: 'ou=people,dc=cluster,dc=local'
  ldap-group-ou: 'ou=groups,dc=cluster,dc=local'
  ldap-bind-user-dn: 'cn=service-account,dc=cluster,dc=local'
  ldap-bind-user: 'service-account'
