apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ldap-config
  namespace: core-system
  labels:
    type: ldap
spec:
  storageClassName: sc-nfs-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ldap-data
  namespace: core-system
  labels:
    type: ldap
spec:
  storageClassName: sc-nfs-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
