apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-global-conf
  namespace: core-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kube-system,default,core-system,core-middleware,core-app,share-app,monitor-app"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kube-system,default,core-system,core-middleware,core-app,share-app,monitor-app"
data:
  ldap_org: 'example team'
  ldap_domain: 'example.com'
  ldap_host: 'ldap-sv.core-system.svc.cluster.local'
  ldap_url: 'ldap://ldap-sv.core-system.svc.cluster.local:389'
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-admin-user
  namespace: core-system
type: Opaque
stringData:
  password: 'example'
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-service-user
  namespace: core-system
type: Opaque
stringData:
  user: 'service-account'
  password: '75d07a81-7c7c-4013-bb02-9d50069a4402'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ldap
  namespace: core-system
  labels:
    app: ldap
spec:
  serviceName: ldap
  selector:
    matchLabels:
      app: ldap
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          image: osixia/openldap:1.5.0
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
          ports:
            - containerPort: 389
              name: openldap
          env:
            - name: LDAP_LOG_LEVEL
              value: "256"
            - name: LDAP_ORGANISATION
              valueFrom:
                configMapKeyRef:
                  name: ldap-global-conf
                  key: ldap_org
            - name: LDAP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: ldap-global-conf
                  key: ldap_domain
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-admin-user
                  key: password
            - name: LDAP_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-admin-user
                  key: password
            - name: LDAP_READONLY_USER
              value: "true"
            - name: LDAP_READONLY_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ldap-service-user
                  key: user
            - name: LDAP_READONLY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-service-user
                  key: password
            - name: LDAP_RFC2307BIS_SCHEMA
              value: "false"
            - name: LDAP_BACKEND
              value: "mdb"
            - name: LDAP_TLS
              value: "false"
            - name: LDAP_REPLICATION
              value: "false"
            - name: KEEP_EXISTING_CONFIG
              value: "false"
            - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
              value: "true"
      volumes:
        - name: ldap-data
          emptyDir: { }
        - name: ldap-config
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap-sv
  name: ldap-sv
  namespace: core-system
spec:
  ports:
    - port: 389
  selector:
    app: ldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-account-manager
  namespace: core-system
  labels:
    app: ldap-account-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap-account-manager
  template:
    metadata:
      labels:
        app: ldap-account-manager
    spec:
      containers:
        - name: ldap-account-manager
          image: ldapaccountmanager/lam:8.0.1
          ports:
            - containerPort: 80
          env:
            - name: LAM_SKIP_PRCONFIGURE
              value: "true"
            - name: LDAP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: ldap-global-conf
                  key: ldap_domain
            - name: LDAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: ldap-global-conf
                  key: ldap_url
            - name: LAM_LANG
              value: zh_CN
            - name: LAM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-admin-user
                  key: password

---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap-account-manager
  name: ldap-account-manager-service
  namespace: core-system
spec:
  ports:
    - port: 80
  selector:
    app: ldap-account-manager
