apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-ca
  namespace: cert-manager
spec:
  secretName: self-signed-ca
  duration: 876000h # 100 year
  issuerRef:
    name: self-signed-issuer
  commonName: "Self CA Certificate"
  isCA: true
