apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-{{var.global.pub-hostname}}
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{var.global.shared-namespace}}"
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{var.global.shared-namespace}}"
  secretName: {{var.global.tls-name}}
  duration: 8760h # 1y
  issuerRef:
    name: self-issuer
  commonName: "Self CA Certificate"
  dnsNames:
    - '{{var.global.pub-host}}'
    - '*.{{var.global.pub-host}}' # 通用公开地址
    - '*.pages.{{var.global.pub-host}}' # gitlab pages 相关地址
    - '*.gitpod.{{var.global.pub-host}}' # gitpod 相关地址
    - '*.ws.gitpod.{{var.global.pub-host}}' # gitpod 相关地址
    - '*.internal.{{var.global.pub-host}}' # 隐私地址
