apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-powercloud-com
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{shared-namespace}}"
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{shared-namespace}}"
  secretName: tls-powercloud-com
  duration: 8760h # 1y
  issuerRef:
    name: self-issuer
  commonName: "Self CA Certificate"
  dnsNames:
    - powercloud.com
    - '*.powercloud.com'
