apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minio
  namespace: core-app
  labels:
    app: minio
spec:
  storageClassName: '{{var.storage.class.security}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
