apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minio
  namespace: core-app
  labels:
    app: minio
spec:
  storageClassName: 'sc-nfs-share'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
