apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: minio
  name: conf-minio
  namespace: core-app
data:
  MINIO_ROOT_USER: 'minio'
  MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER: '(&(uid=%s)(memberOf=cn=admin,ou=groups,dc=cluster,dc=local))'
  MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER: '(&(objectClass=groupOfNames)(member=%d))'
  auto.sh: |
    #!/usr/bin/env bash
    sleep 10
    mc config host add minio http://127.0.0.1:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} --api S3v4
    mc admin policy set minio consoleAdmin group=cn=admin,ou=groups,dc=cluster,dc=local
    while true; do
        if [ -f "/exit.hook" ]; then
            break 
        fi
        sleep 1
    done
    exit 0
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: minio
  name: secret-minio
  namespace: core-app
stringData:
  MINIO_ROOT_PASSWORD: 'minio123'
