apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-minio
  namespace: core-app
  labels:
    app: minio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: {{var.ingress.class.public}}
  tls:
    - hosts:
        - s3.{{var.global.public.host}}
        - minio.internal.{{var.global.public.host}}
      secretName: {{var.global.public.tls-name}}
  rules:
    - host: s3.{{var.global.public.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-minio
                port:
                  name: minio-s3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-minio-console
  namespace: core-app
  labels:
    app: minio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: {{var.ingress.class.private}}
  tls:
    - hosts:
        - minio.{{var.global.private.host}}
      secretName: {{var.global.private.tls-name}}
  rules:
    - host: minio.{{var.global.private.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-minio
                port:
                  name: minio-console
