apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-data
  namespace: core-middle
  labels:
    app: redis
spec:
  storageClassName: '{{default-storage-class}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
