apiVersion: v1
kind: Secret
metadata:
  name: secret-redis
  namespace: core-middle
  labels:
    app: redis
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{var.global.shared-namespace}}"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{var.global.shared-namespace}}"
type: Opaque
stringData:
  password: '{{var.redis.password}}'  # <1>
