
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-v2ray
  namespace: share-app
data:
  config.json: |
    {
      "inbounds": [
        {
          "port": 8080,
          "listen": "0.0.0.0",
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                "id": "{{v2ray.uuid}}"
              }
            ]
          },
          "streamSettings": {
            "network": "ws",
            "wsSettings": {
              "acceptProxyProtocol": false,
              "headers": {
                "Host": "api.{{var.global.pub-host}}"
              },
              "path": "/"
            }
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-v2ray
  namespace: share-app
spec:
  serviceName: svc-alert-manager
  selector:
    matchLabels:
      app: v2ray
  replicas: 1
  template:
    metadata:
      labels:
        app: v2ray
    spec:
      containers:
        - name: v2ray
          image: "docker.io/v2fly/v2fly-core:v4.44.0"
          args:
            - v2ray
            - -c
            - /data/config.json
          volumeMounts:
            - name: conf
              mountPath: /data/
      volumes:
        - name: conf
          configMap:
            name: conf-v2ray
---
apiVersion: v1
kind: Service
metadata:
  name: svc-v2ray
  namespace: share-app
spec:
  #  type: LoadBalancer
  ports:
    - port: 8080
      name: v2ray
  selector:
    app: v2ray
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-v2ray
  namespace: share-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.{{var.global.pub-host}}
      secretName: {{var.global.tls-name}}
  rules:
    - host: api.{{var.global.pub-host}}
      http:
        paths:
          - path: /api/info
            pathType: Prefix
            backend:
              service:
                name: svc-v2ray
                port:
                  name: v2ray
