apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-v2ray
  namespace: share-app
data:
  config.json: |
    {
      "inbounds": [
        {
          "port": 8080,
          "listen": "0.0.0.0",
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                "id": "{{v2ray.uuid}}"
              }
            ]
          },
          "streamSettings": {
            "network": "ws",
            "wsSettings": {
              "acceptProxyProtocol": false,
              "headers": {
                "Host": "api.{{var.global.pub-host}}" 
              },
              "path": "/"
            }
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }
