apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nexus-data
  namespace: core-app
  labels:
    app: nexus
spec:
  storageClassName: sc-nfs-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
