apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus3-nginx-conf
  namespace: core-app
  labels:
    type: nexus3
data:
  default.conf: |
    server_tokens off;
  web-panel.conf: |
    server{
    listen       80;
    listen  [::]:80;
    location / {
    proxy_http_version 1.1;
    proxy_pass http://127.0.0.1:8081; # <1>
    proxy_set_header Host $host;
    proxy_buffering off;
    client_max_body_size 0;
    proxy_connect_timeout 3600s;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    send_timeout 3600s;
    proxy_request_buffering off;
    }
    }
  docker.conf: |
    upstream nexus_docker_hosted {
    server 127.0.0.1:10000; # <2>
    }
    upstream nexus_docker_group {
    server 127.0.0.1:10001; # <3>
    }
    server{
    listen 81;
    listen  [::]:81;
    client_max_body_size 10G;
    chunked_transfer_encoding on;
    set $upstream "nexus_docker_hosted";
    if ( $request_method ~* 'GET') {
    set $upstream "nexus_docker_group";
    }
    if ($request_uri ~ '/search') {
    set $upstream "nexus_docker_hosted";
    }
    location / {
    proxy_pass http://$upstream;
    proxy_set_header Host $host;
    proxy_connect_timeout 3600;
    proxy_send_timeout 3600;
    proxy_read_timeout 3600;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto http;
    }
    }
