apiVersion: v1
kind: Secret
metadata:
  name: secret-postgres-root
  namespace: core-middle
  labels:
    app: postgres
type: Opaque
stringData:
  username: 'postgres'
  password: 'postgres-admin-password' # <1>
