apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nexus-data
  namespace: core-app
  labels:
    app: nexus
spec:
  storageClassName: '{{var.storage.class.security}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
