apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-nexus-nginx
  namespace: core-app
  labels:
    app: nexus
data:
  default.conf: |
    server_tokens off;
  web-panel.conf: |
    server{
    listen       80;
    listen  [::]:80;
    location / {
    proxy_http_version 1.1;
    proxy_pass http://127.0.0.1:8081; # <1>
    proxy_buffering off;
    client_max_body_size 0;
    proxy_connect_timeout 3600s;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    send_timeout 3600s;
    proxy_request_buffering off;
    }
    }
  docker-public.conf: |
    upstream nexus_public_docker_hosted {
    server 127.0.0.1:11000; # <2>
    }
    upstream nexus_public_docker_group {
    server 127.0.0.1:11001; # <3>
    }
    server{
    listen 81;
    listen  [::]:81;
    client_max_body_size 10G;
    chunked_transfer_encoding on;
    set $upstream "nexus_public_docker_hosted";
    if ( $request_method ~* 'GET') {
    set $upstream "nexus_public_docker_group";
    }
    if ($request_uri ~ '/search') {
    set $upstream "nexus_public_docker_hosted";
    }
    location / {
    proxy_pass http://$upstream;
    proxy_connect_timeout 3600s;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_set_header Host $host;
    proxy_buffering off;
    client_max_body_size 0;
    send_timeout 3600s;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_request_buffering off;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    }
    }

  maven.conf: |
    
    upstream nexus_maven_hosted {
    server 127.0.0.1:12000;
    }
    upstream nexus_maven_group {
    server 127.0.0.1:12001;
    }
    server{
    listen 82;
    listen  [::]:82;
    client_max_body_size 10G;
    chunked_transfer_encoding on;
    set $upstream "nexus_maven_hosted";
    if ( $request_method ~* 'GET') {
    set $upstream "nexus_maven_group";
    }
    location / {
    proxy_pass http://$upstream;
    proxy_connect_timeout 3600s;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_set_header Host $host;
    proxy_buffering off;
    client_max_body_size 0;
    send_timeout 3600s;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_request_buffering off;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    }
    server{
    listen 12001;
    listen  [::]:12001;
    client_max_body_size 10G;
    chunked_transfer_encoding on;
    location / {
    proxy_pass http://127.0.0.1/repository/maven-group/;
    proxy_set_header Host $host;
    proxy_buffering off;
    client_max_body_size 0;
    send_timeout 3600s;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_request_buffering off;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    }
    server{
    listen 12000;
    listen  [::]:12000;
    client_max_body_size 10G;
    chunked_transfer_encoding on;
    location / {
    proxy_pass http://127.0.0.1/repository/maven-host/;
    proxy_set_header Host $host;
    proxy_buffering off;
    client_max_body_size 0;
    send_timeout 3600s;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_request_buffering off;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    }

  rpm.conf: |
    upstream nexus_rpm_hosted {
    server 127.0.0.1:13000;
    }
    upstream nexus_rpm_group {
    server 127.0.0.1:13001;
    }
    server{
    listen 83;
    listen  [::]:83;
    client_max_body_size 10G;
    chunked_transfer_encoding on;
    set $upstream "nexus_rpm_hosted";
    if ( $request_method ~* 'GET') {
    set $upstream "nexus_rpm_group";
    }
    location / {
    proxy_pass http://$upstream;
    proxy_connect_timeout 3600s;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_set_header Host $host;
    proxy_buffering off;
    client_max_body_size 0;
    send_timeout 3600s;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_request_buffering off;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    }
    server{
    listen 13001;
    listen  [::]:13001;
    client_max_body_size 10G;
    chunked_transfer_encoding on;
    location / {
    proxy_pass http://127.0.0.1/repository/rpm-group/;
    proxy_set_header Host $host;
    proxy_buffering off;
    client_max_body_size 0;
    send_timeout 3600s;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_request_buffering off;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    }
    server{
    listen 13000;
    listen  [::]:13000;
    client_max_body_size 10G;
    chunked_transfer_encoding on;
    location / {
    proxy_pass http://127.0.0.1/repository/rpm-host/;
    proxy_set_header Host $host;
    proxy_buffering off;
    client_max_body_size 0;
    send_timeout 3600s;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_request_buffering off;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    }
