apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-nexus
  namespace: core-app
  labels:
    app: nexus
spec:
  serviceName: svc-nexus
  selector:
    matchLabels:
      app: nexus
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:3.40.1
          resources:
            requests:
              memory: 3Gi
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"
        - name: nginx
          image: nginx:1.21.1
          volumeMounts:
            - name: nginx-data
              mountPath: /etc/nginx/conf.d/

      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: pvc-nexus-data
        - name: nginx-data
          configMap:
            name: conf-nexus-nginx
