apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nexus
  namespace: core-app
  labels:
    app: nexus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # <1>
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nexus.internal.{{var.global.pub-host}}
        - registry.internal.{{var.global.pub-host}}
        - maven.internal.{{var.global.pub-host}}
      secretName: {{var.global.tls-name}}
  rules:
    - host: nexus.internal.{{var.global.pub-host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-web
    - host: registry.internal.{{var.global.pub-host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-docker
    - host: maven.internal.{{var.global.pub-host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-maven
