apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nexus
  namespace: core-app
  labels:
    app: nexus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # <1>
spec:
  ingressClassName: {{var.ingress.class.private}}
  tls:
    - hosts:
        - nexus.{{var.global.private.host}}
      secretName: {{var.global.private.tls-name}}
  rules:
    - host: nexus.{{var.global.private.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nexus-public
  namespace: core-app
  labels:
    app: nexus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # <1>
spec:
  ingressClassName: {{var.ingress.class.public}}
  tls:
    - hosts:
        - registry.{{var.global.public.host}}
        - repos.{{var.global.public.host}}
      secretName: {{var.global.public.tls-name}}
  rules:
    - host: registry.{{var.global.public.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-docker
    - host: repos.{{var.global.public.host}}
      http:
        paths:
          - path: /maven
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-maven
          - path: /yum
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-yum
          - path: /apt
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-apt
