apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nexus
  namespace: core-app
  labels:
    app: nexus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # <1>
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nexus.internal.d7z.net
        - registry.d7z.net
        - repos.d7z.net
      secretName: tls-d7z-net
  rules:
    - host: nexus.internal.d7z.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-web
    - host: registry.d7z.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-docker
    - host: repos.d7z.net
      http:
        paths:
          - path: /maven
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-maven
          - path: /yum
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-yum
          - path: /apt
            pathType: Prefix
            backend:
              service:
                name: svc-nexus
                port:
                  name: nexus-apt
