apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rook-nfs-local
  namespace: rook-nfs
  labels:
    app: rook-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: sc-rook-nfs-local
  volumeMode: Filesystem
  volumeName: pv-rook-nfs-local # 指定关联的PV 名称
