apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: rook-nfs
  name: '{{var.storage.class.security}}'
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  exportName: local-share
  nfsServerName: rook-nfs
  nfsServerNamespace: rook-nfs
provisioner: nfs.rook.io/rook-nfs-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
