apiVersion: v1
kind: Secret
metadata:
  name: secret-cert-manager-var.cloudflare.api.token
  namespace: cert-manager
type: Opaque
stringData:
  # 需要修改为实际数据
  api-token: '{{var.cloudflare.api.token}}' # <1>
