apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-dns01-cloudflare-1
  namespace: cert-manager
spec:
  acme:
    privateKeySecretRef:
      name: lets-encrypt-dns01
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            email: '{{cloudflare-email}}' # <1>
            apiTokenSecretRef:
              name: secret-cert-manager-cloudflare-api-token # <2>
              key: api-token
