apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-dns01-cloudflare-1
  namespace: cert-manager
spec:
  acme:
    privateKeySecretRef:
      name: lets-encrypt-dns01
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            email: '<请填写你的 CloudFlare 账户邮箱信息>' # <1>
            apiTokenSecretRef:
              name: secret-cert-manager-var.cloudflare.api.token # <2>
              key: api-token
