apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 'cert-{{var.deploy.host.name}}'
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{var.shared.namespace}}" # <1>
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  # <2>
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"  # <3>
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{var.shared.namespace}}"  # <4>
  privateKey:
    algorithm: RSA
    size: 4096
  dnsNames: # <5>
    - '{{var.deploy.host}}'
    - '*.{{var.deploy.host}}'
    - 'pages.{{var.deploy.host}}'
    - '*.pages.{{var.deploy.host}}'
  issuerRef:
    kind: ClusterIssuer
    name: issuer-dns01-cloudflare-1  # <6>
  secretName: 'tls-{{var.deploy.host.name}}'
