apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: web-proxy
  name: conf-web-proxy
  namespace: share-app
data:
  pve.conf: |
    server{
    listen [::]:80;
    listen 80;
    server_name pve.{{var.global.pub-host}}; # <1>
    set $proxy_url 'https://10.0.0.254:8006'; # <2>
    location / {
        proxy_http_version 1.1; # <3>
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass $proxy_url;
        proxy_buffering off;
        client_max_body_size 0; # <4>
        proxy_connect_timeout 3600s;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        send_timeout 3600s;
    }
    }
