apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web-proxy
  namespace: share-app
  labels:
    app: web-proxy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: {{var.ingress.class.public}}
  tls:
    - hosts:
        - pve.{{var.global.public.host}}
      secretName: {{var.global.public.tls-name}}
  rules:
    - host: pve.{{var.global.public.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-web-proxy
                port:
                  name: web
