apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web-proxy
  namespace: share-app
  labels:
    app: web-proxy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx-private
  tls:
    - hosts:
        - pve.d7z.net
      secretName: tls-pub-d7z
  rules:
    - host: pve.d7z.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-web-proxy
                port:
                  name: web
