apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-alert-manager
  namespace: monitor-app
  labels:
    app: alert-manager
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: {{var.ingress.class.private}}
  tls:
    - hosts:
        - alert-manager.internal.{{var.global.private.host}}
      secretName: {{var.global.private.tls-name}}
  rules:
    - host: alert-manager.{{var.global.private.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-alert-manager
                port:
                  name: alert-manager
