apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-gitea
  namespace: core-app
  labels:
    app: gitea
spec:
  serviceName: svc-gitea
  selector:
    matchLabels:
      app: gitea
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.17.1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: svc-gitea
  namespace: core-app
spec:
  ports:
    - name: gitea-web
      protocol: TCP
      port: 3000
  selector:
    app: gitea

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gitea
  namespace: core-app
  labels:
    app: gitea
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # <1>
spec:
  ingressClassName: {{var.ingress.class.public}}
  tls:
    - hosts:
        - gitea.{{var.global.public.host}}
      secretName: {{var.global.public.tls-name}}
  rules:
    - host: gitea.{{var.global.public.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-gitea
                port:
                  name: gitea-web
