apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
  namespace: monitor-app
  labels:
    app: grafana
spec:
  storageClassName: '{{var.storage.class.fast}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
