apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb-data
  namespace: core-middle
spec:
  storageClassName: cluster-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
