apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-server
  namespace: core-middle
  labels:
    app: mariadb-server
spec:
  serviceName: mariadb-server
  selector:
    matchLabels:
      app: mariadb-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb-server
    spec:
      containers:
        - name: mariadb-server
          image: mariadb:10.8
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mariadb-root
                  key: password
            - name: MARIADB_ROOT_HOST
              value: "%"
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: pvc-mariadb-data
