apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: home-page
  name: conf-home-page
  namespace: share-app
data:
  home.conf: |
    resolver kube-dns.kube-system.svc.cluster.local valid=10s;
      server{
      listen [::]:80 default_server;
      listen 80 default_server;
      location / {
      proxy_http_version 1.1;
      proxy_pass http://docs.pages.d7z.net/home/;
      proxy_buffering off;
      proxy_set_header Host docs.pages.d7z.net;
      client_max_body_size 0;
      proxy_connect_timeout 3600s;
      proxy_read_timeout 3600s;
      proxy_send_timeout 3600s;
      send_timeout 3600s;
      }
    }
