apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-local-pv-share
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1000Gi
  local:
    # 指定挂载的目录
    path: /share
    # 配置节点亲和性
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node-worker-01 # 指定部署在 node-worker-01 节点上，可根据实际需求更改
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-local-sc-share
  volumeMode: Filesystem
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-local-sc-share
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-local-pvc-share
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-local-sc-share
  volumeMode: Filesystem
  volumeName: nfs-local-pv-share # 指定关联的PV 名称
