apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitpod
    component: ws-proxy
    kind: service
  name: ws-proxy-lb
  namespace: dev-ops
spec:
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    app: gitpod
    component: ws-proxy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
