apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-data
  namespace: core-middle
  labels:
    type: redis
spec:
  storageClassName: cluster-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
