apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
  namespace: core-middle
  labels:
    app: redis-server
    type: redis
spec:
  serviceName: redis-server
  selector:
    matchLabels:
      app: redis-server
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
        type: redis
    spec:
      containers:
        - name: redis-server
          image: redis:7
          command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
            - '--port 6379'
            - "--requirepass $(REDIS_PASSWORD)"
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-conf
              mountPath: /usr/local/etc/redis
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-redis
                  key: password
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: pvc-redis-data
        - name: redis-conf
          configMap:
            name: redis-conf
