apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool
  namespace: metallb-system
spec:
  addresses:
    # 根据实际需求自行配置
    - 10.0.0.35-10.0.0.39 # <1>
#   - 10.0.2.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-net
  namespace: metallb-system
spec:
  ipAddressPools:
    - primary-pool
