apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: nfs-server
  namespace: rook-nfs
spec:
  replicas: 1
  exports:
    - name: local-share
      server:
        accessMode: ReadWrite
        squash: "none"
      persistentVolumeClaim:
        claimName: nfs-local-pvc-share
  annotations:
    rook: nfs
