## 测试
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-test-pvc
spec:
  storageClassName: cluster-share
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
