apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nfs-server
  name: cluster-share
parameters:
  exportName: local-share
  nfsServerName: nfs-server
  nfsServerNamespace: rook-nfs
provisioner: nfs.rook.io/rook-nfs-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
