name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: 编译项目
        run: |
          sudo apt install -y wget
          wget https://raw.githubusercontent.com/d7z-team/asciidoc-static-pages/main/setup-deb.sh -O /tmp/setup.sh
          chmod +x /tmp/setup.sh
          /tmp/setup.sh `pwd`
      - name: 发布 Web 页面
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
