apiVersion: v1
kind: Secret
metadata:
  name: secret-ldap-admin
  namespace: core-system
  labels:
    app: ldap
type: Opaque
stringData:
  password: '{{var.ldap.admin.password}}' # <1>
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-ldap-service
  namespace: core-system
  labels:
    app: ldap
  annotations: # <2>
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{var.global.shared-namespace}}"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{var.global.shared-namespace}}"
type: Opaque
stringData:
  password: 'service-account' # <3>
