apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ldap
  namespace: core-system
  labels:
    app: ldap
spec:
  storageClassName: '{{var.storage.class.security}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
